backend:
  name: git-gateway
  repo: klrfl/personal-site
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: public/assets/uploads
public_folder: /assets/uploads
media_library:
  name: uploadcare
  config:
    publicKey: e3d7463f1b8b53318662
  settings:
    autoFilename: true
    defaultOperations: '/resize/800x600/'

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "image",
          name: "image",
          widget: "object",
          required: false,
          fields:
            [
              {
                label: "Image URL",
                name: "url",
                widget: "image",
                required: false,
              },
              {
                label: "Image alt text",
                name: "alt",
                widget: "string",
                required: false,
              },
            ],
        }
      - { label: "tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "journal"
    label: "Journal"
    folder: "src/content/journal"
    create: true
    slug: "{{slug}}"
    fields: 
      - {name: "title", label: "Title", widget: "string"}
      - {name: "day", label: "Day", widget: "number"}
      - {
          label: "image",
          name: "image",
          widget: "object",
          required: false,
          fields:
            [
              {
                label: "Image URL",
                name: "url",
                widget: "image",
                required: false,
              },
              {
                label: "Image alt text",
                name: "alt",
                widget: "string",
                required: false,
              },
            ],
        }
      - {name: "created_at", label: "Created at", widget: "datetime"}
      - {name: "body", label: "Body", widget: "markdown"}
